let allFruits=[
    {
        id:1,
        name:"Mango",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukm/ukmam/ukmammo027.mp3"
    },
    {
        id:2,
        name:"Apple",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukapp/ukappen014.mp3",
    },
    {
        id:3,
        name:"Pineapple",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukp/ukpil/ukpilot019.mp3",
    },
    {
        id:4,
        name:"Orange",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uko/ukora/ukorang001.mp3",
    },
    {
        id:5,
        name:"Guava",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgua/ukguate003.mp3",
    },
    {
        id:6,
        name:"Grape",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgra/ukgranu004.mp3",
    },
    {
        id:7,
        name:"Watermealon",
        source:"https://dictionary.cambridge.org/media/english/us_pron/w/wat/water/watermelon.mp3",
    },
    {
        id:8,
        name:"Apricot",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukapp/ukappro010.mp3",
    },
    {
        id:9,
        name:"Durian",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/e/epd/epd09/epd09329.mp3",
    },
    {
        id:10,
        name:"Kiwi",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukk/ukkit/ukkit__013.mp3",
    },
    {
        id:11,
        name:"Banana",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukb/ukbal/ukballs018.mp3",
    },
    {
        id:12,
        name:"Papaya",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukp/ukpan/ukpanor025.mp3",
    },
    {
        id:13,
        name:"Passsion fruit",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/uka34/uka34123.mp3",
    },
    {
        id:14,
        name:"Dragon fruit",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/c/cdo/cdo03/cdo0318ukdrag0455.mp3",
    },

    {
        id:15,
        name:"Lemon",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukl/uklei/ukleisu005.mp3",
    },

    {
        id:16,
        name:"Mangosteen",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/c/cdo/cdo03/cdo0318ukmang0821.mp3",
    },

    {
        id:17,
        name:"Pomegranate",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukp/ukpol/ukpolys011.mp3",
    },

    {
        id:18,
        name:"Strawberry",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uks/ukstr/ukstrat010.mp3",
    },
    {
        id:19,
        name:"Jack fruit",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/c/cdo/cdo03/cdo0319ukjack0885.mp3",
    },
    {
        id:20,
        name:"Rambutan",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/e/epd/epd23/epd23675.mp3",
    },


];

let allVegetables=[
    {
        id:1,
        name:"Beetroot",
        source: "https://dictionary.cambridge.org/media/english/uk_pron/u/ukb/ukbee/ukbeer_006.mp3",
    },
    {
        id:2,
        name:"Cabbage",
        source:"https://dictionary.cambridge.org/media/english/us_pron/c/cab/cabba/cabbage.mp3",
    },
    {
        id:3,
        name:"Capsicum",
        source:"https://dictionary.cambridge.org/media/english/us_pron/u/usc/uscan/uscanoo021.mp3" ,
    },
    {
        id:4,
        name:"Carrot",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcar/ukcarap002.mp3",
    },
    {
        id:5,
        name:"Cucumber",
        source:"https://dictionary.cambridge.org/media/english/us_pron/c/cuc/cucum/cucumber.mp3" ,
    },
    {
        id:6,
        name:"Eggplant",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uke/ukeff/ukeffor011.mp3",
    },
    {
        id:7,
        name:"Garlic ",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgan/ukganja028.mp3",
    },
    {
        id:8,
        name:"Ginger",
        source: "https://dictionary.cambridge.org/media/english/uk_pron/u/ukg/ukgig/ukgigan021.mp3",
    },
    {
        id:9,
        name:"Mushroom",
        source:"https://dictionary.cambridge.org/media/english/us_pron/m/mus/mushr/mushroom.mp3" ,
    },
    {
        id:10,
        name:"Pumpkins",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukp/ukpum/ukpumme004.mp3",
    },
    {
        id:11,
        name:"Onion",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uko/ukomn/ukomniv012.mp3",
    },
    {
        id:12,
        name:"Soy bean",
        source:"https://dictionary.cambridge.org/media/english/us_pron/c/cdo/cdo03/cdo0318ussoyb4645.mp3",
    },
    {
        id:13,
        name:"Broccoli",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukb/ukbri/ukbrit_024.mp3",
    },
    {
        id:14,
        name:"Asparagus",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukasi/ukaside008.mp3",
    },
    {
        id:15,
        name:"Corn",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcor/ukcoran024.mp3",
    },
];


let allAnimals=[
    {
        id:1,
        name:"Elephant",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uke/ukele/ukelect016.mp3",
    },
    {
        id:2,
        name:"Dog",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukd/ukdoc/ukdocud022.mp3",
    },
    {
        id:3,
        name:"Baboon",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukazt/ukazt__012.mp3",
    },
    {
        id:4,
        name:"Camel",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcam/ukcambo005.mp3",
    },
    {
        id:5,
        name:"Bear",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukb/ukban/ukbanqu030.mp3",
    },
    {
        id:6,
        name:"Tiger",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukt/uktic/uktickl024.mp3",
    },
    {
        id:7,
        name:"Sheep",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uks/ukshe/uksheat009.mp3",
    },
    {
        id:8,
        name:"Rhinoceros",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukr/ukrew/ukrewou020.mp3",
    },
    {
        id:9,
        name:"Lion",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukl/uklin/uklink_010.mp3",
    },
    {
        id:10,
        name:"Cat",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcas/ukcaste011.mp3",
    },
    {
        id:11,
        name:"Frog",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukf/ukfri/ukfrill022.mp3",
    },
    {
        id:12,
        name:"Crocodile",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcri/ukcripp029.mp3",
    },
    {
        id:13,
        name:"Deer",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukd/ukddt/ukddt__026.mp3",
    },
    {
        id:14,
        name:"Fox",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukf/ukfou/ukfours005.mp3",
    },
    {
        id:15,
        name:"Squirrel",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uks/uksqu/uksquee016.mp3",
    },
];