


let allAnimals=[
    {
        id:1,
        name:"Elephant",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uke/ukele/ukelect016.mp3",
    },
    {
        id:2,
        name:"Dog",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukd/ukdoc/ukdocud022.mp3",
    },
    {
        id:3,
        name:"Baboon",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukazt/ukazt__012.mp3",
    },
    {
        id:4,
        name:"Camel",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcam/ukcambo005.mp3",
    },
    {
        id:5,
        name:"Bear",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukb/ukban/ukbanqu030.mp3",
    },
    {
        id:6,
        name:"Tiger",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukt/uktic/uktickl024.mp3",
    },
    {
        id:7,
        name:"Sheep",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uks/ukshe/uksheat009.mp3",
    },
    {
        id:8,
        name:"Rhinoceros",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukr/ukrew/ukrewou020.mp3",
    },
    {
        id:9,
        name:"Lion",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukl/uklin/uklink_010.mp3",
    },
    {
        id:10,
        name:"Cat",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcas/ukcaste011.mp3",
    },
    {
        id:11,
        name:"Frog",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukf/ukfri/ukfrill022.mp3",
    },
    {
        id:12,
        name:"Crocodile",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukc/ukcri/ukcripp029.mp3",
    },
    {
        id:13,
        name:"Deer",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukd/ukddt/ukddt__026.mp3",
    },
    {
        id:14,
        name:"Fox",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/ukf/ukfou/ukfours005.mp3",
    },
    {
        id:15,
        name:"Squirrel",
        source:"https://dictionary.cambridge.org/media/english/uk_pron/u/uks/uksqu/uksquee016.mp3",
    },
];
